[package]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "gradient"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
image = {version = "0.23.14", default_features = false, features = ["png"]}
rand = "0.8.4"
tincture = "0.5.0"

[profile.release]
codegen-units = 1
lto = "fat"
